### ISSUE TITLE
Is there a way to clear a point or to set a color on a new point?

### ISSUE THREAD

**Issue by hparadiz** [NorthIsUp/orbital2#2]
So I'm using this to show visitors on our site as they come in. I'm trying to also get rid of old points and to change the colors of points depending on which specific domain they come in from. Is this currently possible?

**Comment by NorthIsUp** [comment]
Just saw this, did you solve your problem?

**Comment by hparadiz** [comment]
Yup. Made a few code changes and added more stuff to the readme.
https://github.com/Akujin/orbital2/commit/20c93bafceeee5786cf60e3d21518b3de21a7ca9

Let me know if you'd like me to make a pull request.

**Comment by NorthIsUp** [comment]
I would love pull requests!

**Comment by hparadiz** [comment]
In case you're wondering here's what I'm using it for:
https://www.dropbox.com/s/o9cxvvh5q8y953u/2013-05-22%2016.57.49.jpg

NodeJS backend. Live feed of currently active open pages on two domains at my work. Would work awesome for any site though.
